name: hackle_furniture_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  easy_stepper: ^0.7.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Furniture - 1/Side 1/
    - assets/images/Furniture - 1/Side 2/
    - assets/images/Furniture - 1/Side 3/
    - assets/images/Furniture - 2/Side 1/
    - assets/images/Furniture - 2/Side 2/
    - assets/images/Furniture - 2/Side 3/
    - assets/images/profile/
    - assets/icons/
    - assets/images/loginpage/
    - assets/images/Head_Page/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
